#Luma_db/Cargo.toml
[package]
name = "luma_db"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "lumadb_client",
    "lumadb_server",
    "lumadb_core",
    "lumadb"
]

[dependencies]
chumsky = "0.9.3"
