[package]
name = "luma-db"
version = "0.1.0"
edition = "2021"

[lib]
name = "lumadb"
path = "src/lumadb/lib.rs"

[[bin]]
name = "server"
path = "src/lumadb_server/server.rs"

[[bin]]
name = "client"
path = "src/lumadb_client/client.rs"
